<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "shift".
 *
 * @property int $id
 * @property string $shift_date
 * @property string $start_date_time
 * @property string $end_date_time
 * @property int|null $client_id
 * @property int|null $emp_id
 * @property int|null $paid
 * @property string|null $paid_on
 * @property string $hour_rate
 * @property string $created_at
 *
 * @property Client $client
 * @property Guard $emp
 */
class Shift extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'shift';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['shift_date', 'start_date_time', 'end_date_time'], 'required'],
            [['client_id', 'emp_id', 'paid'], 'integer'],
            [['paid_on', 'created_at'], 'safe'],
            [['shift_date', 'start_date_time', 'end_date_time', 'hour_rate'], 'string', 'max' => 1000],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Client::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['emp_id'], 'exist', 'skipOnError' => true, 'targetClass' => Guard::className(), 'targetAttribute' => ['emp_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'shift_date' => Yii::t('backend', 'Date'),
            'start_date_time' => Yii::t('backend', 'Start Time'),
            'end_date_time' => Yii::t('backend', 'End Time'),
            'client_id' => Yii::t('backend', 'Client/Site'),
            'emp_id' => Yii::t('backend', 'Guard'),
            'paid' => Yii::t('backend', 'Paid'),
            'paid_on' => Yii::t('backend', 'Paid On'),
            'hour_rate' => Yii::t('backend', 'Hour Rate'),
            'created_at' => Yii::t('backend', 'Created At'),
        ];
    }

    /**
     * Gets query for [[Client]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\ClientQuery
     */
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }

    /**
     * Gets query for [[Emp]].
     *
     * @return \yii\db\ActiveQuery|\common\models\query\GuardQuery
     */
    public function getEmp()
    {
        return $this->hasOne(Guard::className(), ['id' => 'emp_id']);
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\ShiftQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ShiftQuery(get_called_class());
    }

    public function beforeSave($insert)
    {
        $this->hour_rate = $this->client->per_hour_rate;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
